### ISSUE TITLE
Show stderr with uniout?

### ISSUE THREAD

**Issue by carlcarl** [moskytw/uniout#1]
I can set sys.stderr to uniout, ex:

```
sys.stderr = uniout.uniout
```

But this will mix stdout and stderr.
Any other recommended way?
Thanks.

**Comment by moskytw** [comment]
There is not better way for now.

But it is a good advice, I will take time to add this feature. :)

**Comment by carlcarl** [comment]
OK, thanks.

**Comment by moskytw** [comment]
It is OK to keep it opening. I will close it after I solve this issue. :)

**Comment by carlcarl** [comment]
OK~~

**Comment by bendwarn** [comment]
It seems to need another object and dress it using stderr like uniout, that is to say unierr.

**Comment by moskytw** [comment]
Yup, you are right. I am planing to write a class to abstract the behaviors of uniout, and then make two instances for stdout and stderr.

**Comment by moskytw** [comment]
@timtan did it for us. Thanks his pull request #4.

**Comment by carlcarl** [comment]
Good~~
