### ISSUE TITLE
Can not install the package by pip install uniout under windows system

### ISSUE THREAD

**Issue by lmw0320** [moskytw/uniout#18]
I had tried many times to install this package by the command: pip install uniout
Its error is :Not found the module named '__builtin__' ， it seems suitlable for python2, but not for python3。
And I had also downloaded the lateset code from github， and tried to install it by hand. It seems no error found.
But I still can not import uniout correctly....
Could you pls tell me how to solve this problem， TIA。

**Comment by cthui** [comment]
我也遇到了同样的问题，希望得到解答

**Comment by lmw0320** [comment]
> 我也遇到了同样的问题，希望得到解答

github上拉取最新的源码，然后按照下面的链接做法，就可以安装成功。我个人测试过了。
https://www.kmp.tw/post/python3installuniout/

**Comment by moskytw** [comment]
If you are using Python 3, you actually don't need this package. Python 3 supports unicodes nicely. Could you let me know your scenario?

**Comment by cthui** [comment]
> 如果你使用的是 Python 3，你实际上不需要这个包。Python 3 很好地支持 unicode。你能告诉我你的情况吗？
我已经解决这个问题了，感谢各位的帮助
