### ISSUE TITLE
Conflict with IPython's auto complete

### ISSUE THREAD

**Issue by timtan** [moskytw/uniout#2]
After import uniout

IPython's autocomplete is now working. 
and the backspace cannot position the cursor to correct position. 

but It doesn't affect the normal python shell if I turn on the feature of auto complete

**Comment by timtan** [comment]
I want to try to solve this problem

**Comment by moskytw** [comment]
Great! :)

**Comment by apua** [comment]
After importing unitout.py, push 'up' buttom will be not working, too. The reason might be the same as autocomplete.
