### ISSUE TITLE
Doesn't Uniout work in Windows?

### ISSUE THREAD

**Issue by moskytw** [moskytw/uniout#6]
Need to find a Windows machine to test it.

**Comment by timtan** [comment]
I just tried.    it works in windows python shell.   but did not work in windows ipython shell

**Comment by moskytw** [comment]
Interesting. I thought it should fail in both Python shell and IPython shell.

I guess it may be an encoding issue. Do you have time to take a look?

**Comment by timtan** [comment]
I may play it in the weekend

**Comment by moskytw** [comment]
Thanks a lot. :)

**Comment by moskytw** [comment]
I close it, because it indeed works on Windows. Maybe you can fire a new issue for the problem on Windows's IPython.
